//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Facturas
    {
        [Display(Name = "#")]
        public int Numero { get; set; }
        [Display(Name = "Rut Cliente")]
        public string Cliente_rut { get; set; }
        [Display(Name = "Id Venta")]
        public int Venta_id { get; set; }
        [Display(Name = "Fecha")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha_factura { get; set; }
        [Display(Name = "Monto Total")]
        public decimal Monto_total { get; set; }
        [Display(Name = "Productos Vendidos")]
        public int Productos_vendidos { get; set; }
        [Display(Name = "Estado")]
        public string Estado_factura { get; set; }
    }
}
