//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pago
    {
        [Display (Name = "#")]
        public int Id { get; set; }
        [Display(Name = "Forma de pago")]
        public int Formas_de_pago_id { get; set; }
        [Display(Name = "Numero de factura")]
        public int Numero_factura { get; set; }
        [Display(Name = "Monto")]
        public decimal Monto { get; set; }
        [Display(Name = "Fecha")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }
        [Display(Name = "Saldo cuenta")]
        public decimal Saldo_cuenta { get; set; }
    }
}
